name: Action Workflow
on: [push]

jobs:
  run-github-action:
     runs-on: 
        ubuntu-latest
     steps:
      - name: list files
        run: |
           pwd
           ls
      - name: Git Checkout action
        uses: actions/checkout@v3.3.0
      - name: List files after Checkout
        run: | 
          pwd
          ls
      - name: Simple Js Action 
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: Gurpreet Singh
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
