name: Action Workflow
on: 
   workflow_dispatch:
   pull_request:
       type: [opened, closed, assigned, reopened]

jobs:
  run-github-action:
     runs-on: 
        ubuntu-latest
     steps:
      - name: list files
        run: |
           pwd
           ls -a
           echo $GITHUB_REPOSITORY
           echo $GITHUB_SHA
           echo $GITHUB_WORKSPACE
           echo "${{github.token}}"
      - name: Git Checkout action
        uses: actions/checkout@v3.3.0
      - name: List files after Checkout
        run: | 
          pwd
          ls -a
      - name: Simple Js Action 
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: Gurpreet Singh
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
